const fs = require('fs');
const data = JSON.parse(fs.readFileSync('data/actors.json','utf8'));

const actors = [
  {
    "id": 100,
    "name": "Aras Bulut İynemli",
    "fullName": "Aras Bulut İynemli",
    "slug": "aras-bulut-iynemli",
    "country": "Turkey",
    "countrySlug": "turkey",
    "born": "August 25, 1990",
    "birthPlace": "Istanbul, Turkey",
    "nationality": "Turkish",
    "profession": ["Actor"],
    "genre": ["Drama", "Action"],
    "bio": "Best known for his lead roles in 'Çukur' and '7. Koğuştaki Mucize'.",
    "image": "",
    "wikipedia": "https://en.wikipedia.org/wiki/Aras_Bulut_%C4%B0ynemli",
    "movies": ["7. Koğuştaki Mucize", "Tamam mıyız?"],
    "dramas": ["Çukur", "İçerde", "Muhteşem Yüzyıl"],
    "costars": ["Dilan Çiçek Deniz", "Çağatay Ulusoy"],
    "awards": ["Golden Butterfly Award"],
    "active": "2009–present",
    "netWorth": "$7 Million",
    "spouse": "None",
    "children": "None"
  },
  {
    "id": 101,
    "name": "Pınar Deniz",
    "fullName": "Pınar Deniz",
    "slug": "pinar-deniz",
    "country": "Turkey",
    "countrySlug": "turkey",
    "born": "November 4, 1993",
    "birthPlace": "Adana, Turkey",
    "nationality": "Turkish",
    "profession": ["Actress"],
    "genre": ["Crime", "Drama", "Romance"],
    "bio": "Rose to international fame for her role as Ceylin in the legal drama 'Yargı'.",
    "image": "",
    "wikipedia": "https://en.wikipedia.org/wiki/P%C4%B1nar_Deniz",
    "movies": ["Aşkın Kıyameti"],
    "dramas": ["Yargı", "Aşk 101", "Vatanım Sensin"],
    "costars": ["Kaan Urgancıoğlu", "Boran Kuzum"],
    "awards": ["Golden Butterfly Award"],
    "active": "2014–present",
    "netWorth": "$3 Million",
    "spouse": "Kaan Yıldırım",
    "children": "None"
  },
  {
    "id": 102,
    "name": "Engin Akyürek",
    "fullName": "Engin Akyürek",
    "slug": "engin-akyurek",
    "country": "Turkey",
    "countrySlug": "turkey",
    "born": "October 12, 1981",
    "birthPlace": "Ankara, Turkey",
    "nationality": "Turkish",
    "profession": ["Actor", "Author"],
    "genre": ["Drama", "Mystery"],
    "bio": "One of Turkey's most internationally recognized actors, known for 'Fatmagül'ün Suçu Ne?'.",
    "image": "",
    "wikipedia": "https://en.wikipedia.org/wiki/Engin_Aky%C3%BCrek",
    "movies": ["Bi Küçük Eylül Meselesi"],
    "dramas": ["Adım Farah", "Kara Para Aşk", "Sefirin Kızı"],
    "costars": ["Tuba Büyüküstün", "Neslihan Atagül"],
    "awards": ["International Emmy Nominee"],
    "active": "2004–present",
    "netWorth": "$10 Million",
    "spouse": "None",
    "children": "None"
  },
  {
    "id": 103,
    "name": "Hande Erçel",
    "fullName": "Hande Erçel",
    "slug": "hande-ercel",
    "country": "Turkey",
    "countrySlug": "turkey",
    "born": "November 24, 1993",
    "birthPlace": "Bandırma, Turkey",
    "nationality": "Turkish",
    "profession": ["Actress", "Model"],
    "genre": ["Rom-Com", "Drama"],
    "bio": "Global star known for 'Sen Çal Kapımı' and her massive social media presence.",
    "image": "",
    "wikipedia": "https://en.wikipedia.org/wiki/Hande_Er%C3%A7el",
    "movies": ["Mest-i Aşk"],
    "dramas": ["Sen Çal Kapımı", "Güneşin Kızları", "Aşk Laftan Anlamaz"],
    "costars": ["Kerem Bürsin", "Burak Deniz"],
    "awards": ["Golden Butterfly Award"],
    "active": "2012–present",
    "netWorth": "$8 Million",
    "spouse": "None",
    "children": "None"
  },
  {
    "id": 104,
    "name": "Alp Navruz",
    "fullName": "Seyit Alp Navruz",
    "slug": "alp-navruz",
    "country": "Turkey",
    "countrySlug": "turkey",
    "born": "January 15, 1990",
    "birthPlace": "Istanbul, Turkey",
    "nationality": "Turkish",
    "profession": ["Actor", "Model"],
    "genre": ["Drama", "Romance"],
    "bio": "Gained fame through 'Fazilet Hanım ve Kızları' and 'Ada Masalı'.",
    "image": "",
    "wikipedia": "https://tr.wikipedia.org/wiki/Alp_Navruz",
    "movies": ["Ceberrut"],
    "dramas": ["Ada Masalı", "Elimi Bırakma", "Yürek Çıkmazı"],
    "costars": ["Ayça Ayşin Turan", "Alina Boz"],
    "awards": ["Turkey Youth Award"],
    "active": "2016–present",
    "netWorth": "$2.5 Million",
    "spouse": "None",
    "children": "None"
  },
  {
    "id": 105,
    "name": "Ebru Şahin",
    "fullName": "Ebru Şahin",
    "slug": "ebru-sahin",
    "country": "Turkey",
    "countrySlug": "turkey",
    "born": "May 18, 1994",
    "birthPlace": "Istanbul, Turkey",
    "nationality": "Turkish",
    "profession": ["Actress"],
    "genre": ["Historical", "Drama"],
    "bio": "Rose to prominence for her lead role in the series 'Hercai'.",
    "image": "",
    "wikipedia": "https://en.wikipedia.org/wiki/Ebru_%C5%9Eahin",
    "movies": ["Şuursuz Aşk"],
    "dramas": ["Hercai", "Destan", "Yüz Yıllık Mucize"],
    "costars": ["Akın Akınözü", "Edip Tepeli"],
    "awards": ["Golden Butterfly Award"],
    "active": "2016–present",
    "netWorth": "$3.5 Million",
    "spouse": "Cedi Osman",
    "children": "None"
  },
  {
    "id": 106,
    "name": "Akın Akınözü",
    "fullName": "Süreyya Akın Akınözü",
    "slug": "akin-akinozu",
    "country": "Turkey",
    "countrySlug": "turkey",
    "born": "September 22, 1990",
    "birthPlace": "Ankara, Turkey",
    "nationality": "Turkish",
    "profession": ["Actor"],
    "genre": ["Drama"],
    "bio": "Widely known for playing Miran in 'Hercai', leading to massive popularity in Latin America.",
    "image": "",
    "wikipedia": "https://en.wikipedia.org/wiki/Ak%C4%B1n_Ak%C4%B1n%C3%B6z%C3%BC",
    "movies": ["Gaffur"],
    "dramas": ["Hercai", "Kaderimin Oyunu", "Tuzak"],
    "costars": ["Ebru Şahin", "Bensu Soral"],
    "awards": ["Premios Nova"],
    "active": "2014–present",
    "netWorth": "$3 Million",
    "spouse": "None",
    "children": "None"
  },
  {
    "id": 107,
    "name": "Neslihan Atagül",
    "fullName": "Neslihan Atagül Doğulu",
    "slug": "neslihan-atagul",
    "country": "Turkey",
    "countrySlug": "turkey",
    "born": "August 20, 1992",
    "birthPlace": "Istanbul, Turkey",
    "nationality": "Turkish",
    "profession": ["Actress"],
    "genre": ["Drama", "Romance"],
    "bio": "Known for her intense dramatic performances in 'Kara Sevda' and 'Sefirin Kızı'.",
    "image": "",
    "wikipedia": "https://en.wikipedia.org/wiki/Neslihan_Atag%C3%BCl",
    "movies": ["Araf"],
    "dramas": ["Kara Sevda", "Sefirin Kızı", "Gecenin Ucunda"],
    "costars": ["Burak Özçivit", "Kadir Doğulu"],
    "awards": ["Tokyo International Film Festival - Best Actress"],
    "active": "2006–present",
    "netWorth": "$6 Million",
    "spouse": "Kadir Doğulu",
    "children": "None"
  },
  {
    "id": 108,
    "name": "Kadir Doğulu",
    "fullName": "Abdulkadir Doğulu",
    "slug": "kadir-dogulu",
    "country": "Turkey",
    "countrySlug": "turkey",
    "born": "April 19, 1982",
    "birthPlace": "Mersin, Turkey",
    "nationality": "Turkish",
    "profession": ["Actor"],
    "genre": ["Drama", "Romance"],
    "bio": "Lead actor known for 'Fatih Harbiye' and 'Vuslat'.",
    "image": "",
    "wikipedia": "https://en.wikipedia.org/wiki/Kadir_Do%C4%9Fulu",
    "movies": ["Bir Hikayem Var"],
    "dramas": ["Fatih Harbiye", "Vuslat", "Muhteşem Yüzyıl: Kösem"],
    "costars": ["Neslihan Atagül", "Devrim Özkan"],
    "awards": [],
    "active": "2010–present",
    "netWorth": "$4 Million",
    "spouse": "Neslihan Atagül",
    "children": "None"
  },
  {
    "id": 109,
    "name": "Burak Deniz",
    "fullName": "Burak Deniz",
    "slug": "burak-deniz",
    "country": "Turkey",
    "countrySlug": "turkey",
    "born": "February 17, 1991",
    "birthPlace": "Istanbul, Turkey",
    "nationality": "Turkish",
    "profession": ["Actor"],
    "genre": ["Rom-Com", "Thriller"],
    "bio": "Star of 'Aşk Laftan Anlamaz' and the crime series 'Bambaşka Biri'.",
    "image": "",
    "wikipedia": "https://en.wikipedia.org/wiki/Burak_Deniz",
    "movies": ["Arada"],
    "dramas": ["Bambaşka Biri", "Maraşlı", "Bizim Hikaye"],
    "costars": ["Hande Erçel", "Alina Boz"],
    "awards": [],
    "active": "2011–present",
    "netWorth": "$5 Million",
    "spouse": "None",
    "children": "None"
  },
  {
    "id": 110,
    "name": "Demet Özdemir",
    "fullName": "Demet Özdemir",
    "slug": "demet-ozdemir",
    "country": "Turkey",
    "countrySlug": "turkey",
    "born": "February 26, 1992",
    "birthPlace": "Izmit, Turkey",
    "nationality": "Turkish",
    "profession": ["Actress", "Dancer"],
    "genre": ["Rom-Com", "Drama"],
    "bio": "Extremely popular for her role in 'Erkenci Kuş'.",
    "image": "",
    "wikipedia": "https://en.wikipedia.org/wiki/Demet_%C3%96zdemir",
    "movies": ["Aşk Taktikleri"],
    "dramas": ["Erkenci Kuş", "Adım Farah", "Doğduğun Ev Kaderindir"],
    "costars": ["Can Yaman", "Engin Akyürek"],
    "awards": ["Golden Butterfly Award"],
    "active": "2013–present",
    "netWorth": "$7 Million",
    "spouse": "Oğuzhan Koç (div.)",
    "children": "None"
  },
  {
    "id": 111,
    "name": "Can Yaman",
    "fullName": "Can Yaman",
    "slug": "can-yaman",
    "country": "Turkey",
    "countrySlug": "turkey",
    "born": "November 8, 1989",
    "birthPlace": "Istanbul, Turkey",
    "nationality": "Turkish",
    "profession": ["Actor", "Model"],
    "genre": ["Rom-Com", "Action"],
    "bio": "Global phenomenon, especially popular in Italy, known for 'Erkenci Kuş'.",
    "image": "",
    "wikipedia": "https://en.wikipedia.org/wiki/Can_Yaman",
    "movies": [],
    "dramas": ["Erkenci Kuş", "Dolunay", "Bay Yanlış", "Viola come il mare"],
    "costars": ["Demet Özdemir", "Özge Gürel"],
    "awards": ["Golden Butterfly Award"],
    "active": "2014–present",
    "netWorth": "$12 Million",
    "spouse": "None",
    "children": "None"
  },
  {
    "id": 112,
    "name": "Özge Gürel",
    "fullName": "Özge Gürel",
    "slug": "ozge-gurel",
    "country": "Turkey",
    "countrySlug": "turkey",
    "born": "February 5, 1987",
    "birthPlace": "Istanbul, Turkey",
    "nationality": "Turkish",
    "profession": ["Actress"],
    "genre": ["Rom-Com", "Drama"],
    "bio": "Known for lead roles in 'Kiraz Mevsimi' and 'Dolunay'.",
    "image": "",
    "wikipedia": "https://en.wikipedia.org/wiki/%C3%96zge_G%C3%BCrel",
    "movies": ["Annem"],
    "dramas": ["Kiraz Mevsimi", "Dolunay", "Sipahi"],
    "costars": ["Serkan Çayoğlu", "Can Yaman"],
    "awards": [],
    "active": "2010–present",
    "netWorth": "$4 Million",
    "spouse": "Serkan Çayoğlu",
    "children": "None"
  },
  {
    "id": 113,
    "name": "Serkan Çayoğlu",
    "fullName": "Serkan Çayoğlu",
    "slug": "serkan-cayoglu",
    "country": "Turkey",
    "countrySlug": "turkey",
    "born": "May 31, 1987",
    "birthPlace": "Germany",
    "nationality": "Turkish",
    "profession": ["Actor", "Model"],
    "genre": ["Drama", "Action"],
    "bio": "Gained fame in 'Kiraz Mevsimi' and the military drama 'Börü'.",
    "image": "",
    "wikipedia": "https://en.wikipedia.org/wiki/Serkan_%C3%87ayo%C4%9Flu",
    "movies": ["Börü"],
    "dramas": ["Kiraz Mevsimi", "Halka", "Bir Zamanlar Kıbrıs"],
    "costars": ["Özge Gürel", "Hande Erçel"],
    "awards": [],
    "active": "2012–present",
    "netWorth": "$4.5 Million",
    "spouse": "Özge Gürel",
    "children": "None"
  },
  {
    "id": 114,
    "name": "İbrahim Çelikkol",
    "fullName": "İbrahim Çelikkol",
    "slug": "ibrahim-celikkol",
    "country": "Turkey",
    "countrySlug": "turkey",
    "born": "February 14, 1982",
    "birthPlace": "Izmit, Turkey",
    "nationality": "Turkish",
    "profession": ["Actor", "Model"],
    "genre": ["Drama", "Action"],
    "bio": "Former basketball player turned actor, known for 'Siyah Beyaz Aşk'.",
    "image": "",
    "wikipedia": "https://en.wikipedia.org/wiki/%C4%B0brahim_%C3%87elikkol",
    "movies": ["Fetih 1453"],
    "dramas": ["Siyah Beyaz Aşk", "Doğduğun Ev Kaderindir", "Kuş Uçuşu"],
    "costars": ["Birce Akalay", "Demet Özdemir"],
    "awards": [],
    "active": "2008–present",
    "netWorth": "$6 Million",
    "spouse": "Mihre Mutlu (div.)",
    "children": "1"
  },
  {
    "id": 115,
    "name": "Birce Akalay",
    "fullName": "Birce Akalay",
    "slug": "birce-akalay",
    "country": "Turkey",
    "countrySlug": "turkey",
    "born": "June 19, 1984",
    "birthPlace": "Istanbul, Turkey",
    "nationality": "Turkish",
    "profession": ["Actress"],
    "genre": ["Drama"],
    "bio": "Famous for her roles in 'Yer Gök Aşk' and 'Siyah Beyaz Aşk'.",
    "image": "",
    "wikipedia": "https://en.wikipedia.org/wiki/Birce_Akalay",
    "movies": ["Nefes: Vatan Sağolsun"],
    "dramas": ["Siyah Beyaz Aşk", "Kuş Uçuşu", "Yer Gök Aşk"],
    "costars": ["İbrahim Çelikkol", "Murat Ünalmış"],
    "awards": [],
    "active": "2006–present",
    "netWorth": "$4 Million",
    "spouse": "Sarp Levendoğlu (div.)",
    "children": "None"
  },
  {
    "id": 116,
    "name": "Uraz Kaygılaroğlu",
    "fullName": "Uraz Kaygılaroğlu",
    "slug": "uraz-kaygilaroglu",
    "country": "Turkey",
    "countrySlug": "turkey",
    "born": "June 30, 1987",
    "birthPlace": "Istanbul, Turkey",
    "nationality": "Turkish",
    "profession": ["Actor"],
    "genre": ["Drama", "Comedy"],
    "bio": "Versatile actor known for 'Sefirin Kızı' and 'Üç Kuruş'.",
    "image": "",
    "wikipedia": "https://en.wikipedia.org/wiki/Uraz_Kayg%C4%B1laro%C4%9Flu",
    "movies": ["Eltilerin Savaşı"],
    "dramas": ["Sefirin Kızı", "Üç Kuruş", "Sakla Beni"],
    "costars": ["Neslihan Atagül", "Ekin Koç"],
    "awards": [],
    "active": "2008–present",
    "netWorth": "$3 Million",
    "spouse": "Melis İşiten (div.)",
    "children": "1"
  },
  {
    "id": 117,
    "name": "Ekin Koç",
    "fullName": "İsmet Ekin Koç",
    "slug": "ekin-koc",
    "country": "Turkey",
    "countrySlug": "turkey",
    "born": "June 21, 1992",
    "birthPlace": "Antalya, Turkey",
    "nationality": "Turkish",
    "profession": ["Actor"],
    "genre": ["Historical", "Crime"],
    "bio": "Gained international attention as Sultan Ahmed in 'Muhteşem Yüzyıl: Kösem'.",
    "image": "",
    "wikipedia": "https://en.wikipedia.org/wiki/Ekin_Ko%C3%A7",
    "movies": ["Bizim İçin Şampiyon"],
    "dramas": ["Muhteşem Yüzyıl: Kösem", "Üç Kuruş", "Uyanış: Büyük Selçuklu"],
    "costars": ["Beren Saat", "Uraz Kaygılaroğlu"],
    "awards": [],
    "active": "2013–present",
    "netWorth": "$4 Million",
    "spouse": "None",
    "children": "None"
  },
  {
    "id": 118,
    "name": "Ayça Ayşin Turan",
    "fullName": "Ayça Ayşin Turan",
    "slug": "ayca-aysin-turan",
    "country": "Turkey",
    "countrySlug": "turkey",
    "born": "October 25, 1992",
    "birthPlace": "Sinop, Turkey",
    "nationality": "Turkish",
    "profession": ["Actress"],
    "genre": ["Drama", "Rom-Com"],
    "bio": "Lead star of Netflix's 'The Protector' and 'Ada Masalı'.",
    "image": "",
    "wikipedia": "https://en.wikipedia.org/wiki/Ay%C3%A7a_Ay%C5%9Fin_Turan",
    "movies": ["Sevimli Tehlikeli"],
    "dramas": ["The Protector", "Ada Masalı", "Meryem"],
    "costars": ["Çağatay Ulusoy", "Alp Navruz"],
    "awards": ["Golden Butterfly Award"],
    "active": "2011–present",
    "netWorth": "$3.5 Million",
    "spouse": "None",
    "children": "None"
  },
  {
    "id": 119,
    "name": "Kaan Urgancıoğlu",
    "fullName": "Kaan Urgancıoğlu",
    "slug": "kaan-urgancioglu",
    "country": "Turkey",
    "countrySlug": "turkey",
    "born": "May 8, 1981",
    "birthPlace": "Izmir, Turkey",
    "nationality": "Turkish",
    "profession": ["Actor"],
    "genre": ["Crime", "Drama"],
    "bio": "Known for his iconic antagonist role in 'Kara Sevda' and lead role in 'Yargı'.",
    "image": "",
    "wikipedia": "https://en.wikipedia.org/wiki/Kaan_Urganc%C4%B1o%C4%9Flu",
    "movies": ["Aşk 101"],
    "dramas": ["Yargı", "Kara Sevda", "Jack Ryan"],
    "costars": ["Pınar Deniz", "Burak Özçivit"],
    "awards": [],
    "active": "2002–present",
    "netWorth": "$5 Million",
    "spouse": "Burcu Denizer",
    "children": "1"
  },
  {
    "id": 120,
    "name": "Boran Kuzum",
    "fullName": "Boran Kuzum",
    "slug": "boran-kuzum",
    "country": "Turkey",
    "countrySlug": "turkey",
    "born": "October 1, 1992",
    "birthPlace": "Ankara, Turkey",
    "nationality": "Turkish",
    "profession": ["Actor"],
    "genre": ["Historical", "Drama"],
    "bio": "Critically acclaimed actor known for 'Vatanım Sensin' and 'Saygı'.",
    "image": "",
    "wikipedia": "https://en.wikipedia.org/wiki/Boran_Kuzum",
    "movies": ["Bihter"],
    "dramas": ["Vatanım Sensin", "Hakan: Muhafız", "Saygı"],
    "costars": ["Miray Daner", "Farah Zeynep Abdullah"],
    "awards": [],
    "active": "2011–present",
    "netWorth": "$2 Million",
    "spouse": "None",
    "children": "None"
  },
  {
    "id": 121,
    "name": "Miray Daner",
    "fullName": "Miray Naz Daner",
    "slug": "miray-daner",
    "country": "Turkey",
    "countrySlug": "turkey",
    "born": "January 15, 1999",
    "birthPlace": "Istanbul, Turkey",
    "nationality": "Turkish",
    "profession": ["Actress"],
    "genre": ["Drama"],
    "bio": "Started as a child actress, rose to fame with 'Medcezir' and 'Vatanım Sensin'.",
    "image": "",
    "wikipedia": "https://en.wikipedia.org/wiki/Miray_Daner",
    "movies": ["Çınar Ağacı"],
    "dramas": ["Vatanım Sensin", "Kuş Uçuşu", "Medcezir"],
    "costars": ["Boran Kuzum", "Birce Akalay"],
    "awards": [],
    "active": "2008–present",
    "netWorth": "$2.5 Million",
    "spouse": "None",
    "children": "None"
  },
  {
    "id": 122,
    "name": "Deniz Baysal",
    "fullName": "Deniz Baysal Yurtcu",
    "slug": "deniz-baysal",
    "country": "Turkey",
    "countrySlug": "turkey",
    "born": "April 5, 1991",
    "birthPlace": "Izmir, Turkey",
    "nationality": "Turkish",
    "profession": ["Actress"],
    "genre": ["Action", "Drama"],
    "bio": "Known for lead roles in 'Fazilet Hanım ve Kızları' and 'Teşkilat'.",
    "image": "",
    "wikipedia": "https://en.wikipedia.org/wiki/Deniz_Baysal",
    "movies": ["7. Koğuştaki Mucize"],
    "dramas": ["Teşkilat", "Fazilet Hanım ve Kızları", "Söz"],
    "costars": ["Çağlar Ertuğrul", "Murat Yıldırım"],
    "awards": [],
    "active": "2011–present",
    "netWorth": "$4 Million",
    "spouse": "Barış Yurtcu",
    "children": "None"
  },
  {
    "id": 123,
    "name": "Çağlar Ertuğrul",
    "fullName": "Çağlar Ertuğrul",
    "slug": "caglar-ertugrul",
    "country": "Turkey",
    "countrySlug": "turkey",
    "born": "November 5, 1987",
    "birthPlace": "Izmir, Turkey",
    "nationality": "Turkish",
    "profession": ["Actor", "Mechanical Engineer"],
    "genre": ["Action", "Rom-Com"],
    "bio": "Won Golden Butterfly for Best Actor for his role in 'Afili Aşk'.",
    "image": "",
    "wikipedia": "https://en.wikipedia.org/wiki/%C3%87a%C4%9Flar_Ertu%C4%9Frul",
    "movies": ["Dağ"],
    "dramas": ["Teşkilat", "Afili Aşk", "Fazilet Hanım ve Kızları"],
    "costars": ["Deniz Baysal", "Burcu Özberk"],
    "awards": ["Golden Butterfly Award"],
    "active": "2012–present",
    "netWorth": "$5 Million",
    "spouse": "None",
    "children": "None"
  },
  {
    "id": 124,
    "name": "Burcu Özberk",
    "fullName": "Burcu Özberk",
    "slug": "burcu-ozberk",
    "country": "Turkey",
    "countrySlug": "turkey",
    "born": "December 12, 1989",
    "birthPlace": "Eskişehir, Turkey",
    "nationality": "Turkish",
    "profession": ["Actress"],
    "genre": ["Rom-Com"],
    "bio": "The 'Queen of Rom-Coms' in Turkey, known for 'Afili Aşk' and 'Aşk Mantık İntikam'.",
    "image": "",
    "wikipedia": "https://en.wikipedia.org/wiki/Burcu_%C3%96zberk",
    "movies": ["Direniş Karatay"],
    "dramas": ["Afili Aşk", "Aşk Mantık İntikam", "Güneşin Kızları"],
    "costars": ["Çağlar Ertuğrul", "İlhan Şen"],
    "awards": ["Golden Butterfly Award"],
    "active": "2013–present",
    "netWorth": "$4.5 Million",
    "spouse": "None",
    "children": "None"
  },
  {
    "id": 125,
    "name": "İlhan Şen",
    "fullName": "İlhan Şen",
    "slug": "ilhan-sen",
    "country": "Turkey",
    "countrySlug": "turkey",
    "born": "December 19, 1989",
    "birthPlace": "Bulgaria",
    "nationality": "Turkish",
    "profession": ["Actor", "Model"],
    "genre": ["Romance", "Drama"],
    "bio": "Model turned actor who gained massive fame with 'Aşk Mantık İntikam'.",
    "image": "",
    "wikipedia": "https://en.wikipedia.org/wiki/%C4%B0lhan_%C5%9Een",
    "movies": ["Biz Böyleyiz"],
    "dramas": ["Aşk Mantık İntikam", "Safir", "Ramo"],
    "costars": ["Burcu Özberk", "Özge Yağız"],
    "awards": ["Best Model of Turkey"],
    "active": "2018–present",
    "netWorth": "$2 Million",
    "spouse": "None",
    "children": "None"
  },
  {
    "id": 126,
    "name": "Özge Yağız",
    "fullName": "Özge Yağız",
    "slug": "ozge-yagiz",
    "country": "Turkey",
    "countrySlug": "turkey",
    "born": "September 26, 1997",
    "birthPlace": "Istanbul, Turkey",
    "nationality": "Turkish",
    "profession": ["Actress"],
    "genre": ["Drama"],
    "bio": "Known as the 'New Turkan Soray', famous for 'Yemin' and 'Baba'.",
    "image": "",
    "wikipedia": "https://en.wikipedia.org/wiki/%C3%96zge_Ya%C4%9Fiz",
    "movies": [],
    "dramas": ["Yemin", "Sol Yanım", "Baba", "Safir"],
    "costars": ["Gökberk Demirci", "İlhan Şen"],
    "awards": [],
    "active": "2018–present",
    "netWorth": "$1.5 Million",
    "spouse": "None",
    "children": "None"
  },
  {
    "id": 127,
    "name": "Murat Yıldırım",
    "fullName": "Murat Yıldırım",
    "slug": "murat-yildirim",
    "country": "Turkey",
    "countrySlug": "turkey",
    "born": "April 13, 1979",
    "birthPlace": "Konya, Turkey",
    "nationality": "Turkish",
    "profession": ["Actor"],
    "genre": ["Drama", "Action"],
    "bio": "Famous for 'Asi' and hosting 'Who Wants to Be a Millionaire?' Turkey.",
    "image": "",
    "wikipedia": "https://en.wikipedia.org/wiki/Murat_Y%C4%B1ld%C4%B1r%C4%B1m_(actor)",
    "movies": ["Ayla: The Daughter of War"],
    "dramas": ["Asi", "Ramo", "Teşkilat"],
    "costars": ["Tuba Büyüküstün", "Esra Bilgiç"],
    "awards": [],
    "active": "1999–present",
    "netWorth": "$15 Million",
    "spouse": "Imane Elbani",
    "children": "1"
  },
  {
    "id": 128,
    "name": "Esra Bilgiç",
    "fullName": "Esra Bilgiç",
    "slug": "esra-bilgic",
    "country": "Turkey",
    "countrySlug": "turkey",
    "born": "October 14, 1992",
    "birthPlace": "Ankara, Turkey",
    "nationality": "Turkish",
    "profession": ["Actress"],
    "genre": ["Historical", "Crime"],
    "bio": "Gained international fame as Halime Hatun in 'Diriliş: Ertuğrul'.",
    "image": "",
    "wikipedia": "https://en.wikipedia.org/wiki/Esra_Bilgi%C3%A7",
    "movies": ["Adanış: Kutsal Kavga"],
    "dramas": ["Diriliş: Ertuğrul", "Ramo", "Kanunsuz Topraklar"],
    "costars": ["Engin Altan Düzyatan", "Murat Yıldırım"],
    "awards": [],
    "active": "2014–present",
    "netWorth": "$5 Million",
    "spouse": "Gökhan Töre (div.)",
    "children": "None"
  },
  {
    "id": 129,
    "name": "Kerem Bürsin",
    "fullName": "Kerem Bürsin",
    "slug": "kerem-bursin",
    "country": "Turkey",
    "countrySlug": "turkey",
    "born": "June 4, 1987",
    "birthPlace": "Istanbul, Turkey",
    "nationality": "Turkish",
    "profession": ["Actor"],
    "genre": ["Rom-Com", "Drama"],
    "bio": "Lived in the US, known for 'Güneşi Beklerken' and 'Sen Çal Kapımı'.",
    "image": "",
    "wikipedia": "https://en.wikipedia.org/wiki/Kerem_B%C3%BCrsin",
    "movies": ["Can Feda"],
    "dramas": ["Sen Çal Kapımı", "Şeref Meselesi", "Ya Çok Seversen"],
    "costars": ["Hande Erçel", "Hafsanur Sancaktutan"],
    "awards": ["Seoul International Drama Award"],
    "active": "2006–present",
    "netWorth": "$9 Million",
    "spouse": "None",
    "children": "None"
  },
  {
    "id": 130,
    "name": "Seranay Sarıkaya",
    "fullName": "Serenay Sarıkaya",
    "slug": "serenay-sarikaya",
    "country": "Turkey",
    "countrySlug": "turkey",
    "born": "July 1, 1992",
    "birthPlace": "Ankara, Turkey",
    "nationality": "Turkish",
    "profession": ["Actress", "Model"],
    "genre": ["Drama", "Fantasy"],
    "bio": "Acclaimed actress known for 'Medcezir', 'Fi', and 'Şahmaran'.",
    "image": "",
    "wikipedia": "https://en.wikipedia.org/wiki/Serenay_Sar%C4%B1kaya",
    "movies": ["Bergen"],
    "dramas": ["Medcezir", "Fi", "Şahmaran", "Aile"],
    "costars": ["Çağatay Ulusoy", "Kıvanç Tatlıtuğ"],
    "awards": ["Golden Butterfly Award"],
    "active": "2006–present",
    "netWorth": "$10 Million",
    "spouse": "None",
    "children": "None"
  },
  {
    "id": 131,
    "name": "Mert Ramazan Demir",
    "fullName": "Mert Ramazan Demir",
    "slug": "mert-ramazan-demir",
    "country": "Turkey",
    "countrySlug": "turkey",
    "born": "January 28, 1998",
    "birthPlace": "Istanbul, Turkey",
    "nationality": "Turkish",
    "profession": ["Actor"],
    "genre": ["Drama"],
    "bio": "Breakout star of the massive hit 'Yalı Çapkını'.",
    "image": "",
    "wikipedia": "https://tr.wikipedia.org/wiki/Mert_Ramazan_Demir",
    "movies": ["UFO"],
    "dramas": ["Yalı Çapkını", "Şahmaran"],
    "costars": ["Afra Saraçoğlu", "Serenay Sarıkaya"],
    "awards": [],
    "active": "2020–present",
    "netWorth": "$1 Million",
    "spouse": "None",
    "children": "None"
  },
  {
    "id": 132,
    "name": "Afra Saraçoğlu",
    "fullName": "Afra Saraçoğlu",
    "slug": "afra-saracoglu",
    "country": "Turkey",
    "countrySlug": "turkey",
    "born": "December 2, 1997",
    "birthPlace": "Edremit, Turkey",
    "nationality": "Turkish",
    "profession": ["Actress"],
    "genre": ["Drama"],
    "bio": "Gained fame with 'Fazilet Hanım ve Kızları' and currently stars in 'Yalı Çapkını'.",
    "image": "",
    "wikipedia": "https://en.wikipedia.org/wiki/Afra_Sara%C3%A7o%C4%9Flu",
    "movies": ["İkinci Şans"],
    "dramas": ["Yalı Çapkını", "Fazilet Hanım ve Kızları", "Yeşilçam"],
    "costars": ["Mert Ramazan Demir", "Çağatay Ulusoy"],
    "awards": [],
    "active": "2016–present",
    "netWorth": "$2 Million",
    "spouse": "None",
    "children": "None"
  },
  {
    "id": 133,
    "name": "Halit Ergenç",
    "fullName": "Halit Ergenç",
    "slug": "halit-ergenc",
    "country": "Turkey",
    "countrySlug": "turkey",
    "born": "April 30, 1970",
    "birthPlace": "Istanbul, Turkey",
    "nationality": "Turkish",
    "profession": ["Actor"],
    "genre": ["Historical", "Drama"],
    "bio": "Legendary actor famous for playing Sultan Suleiman in 'Muhteşem Yüzyıl'.",
    "image": "",
    "wikipedia": "https://en.wikipedia.org/wiki/Halit_Ergen%C3%A7",
    "movies": ["Babam ve Oğlum"],
    "dramas": ["Muhteşem Yüzyıl", "Vatanım Sensin", "Binbir Gece"],
    "costars": ["Bergüzar Korel", "Meryem Uzerli"],
    "awards": ["Golden Butterfly Award"],
    "active": "1996–present",
    "netWorth": "$20 Million",
    "spouse": "Bergüzar Korel",
    "children": "3"
  },
  {
    "id": 134,
    "name": "Bergüzar Korel",
    "fullName": "Bergüzar Gökçe Korel",
    "slug": "berguzar-korel",
    "country": "Turkey",
    "countrySlug": "turkey",
    "born": "August 27, 1982",
    "birthPlace": "Istanbul, Turkey",
    "nationality": "Turkish",
    "profession": ["Actress"],
    "genre": ["Drama"],
    "bio": "Known for 'Binbir Gece' and 'Vatanım Sensin'.",
    "image": "",
    "wikipedia": "https://en.wikipedia.org/wiki/Berg%C3%BCzar_Korel",
    "movies": ["Kurtlar Vadisi Irak"],
    "dramas": ["Binbir Gece", "Vatanım Sensin", "Karadayı"],
    "costars": ["Halit Ergenç", "Kenan İmirzalıoğlu"],
    "awards": ["Golden Butterfly Award"],
    "active": "2006–present",
    "netWorth": "$10 Million",
    "spouse": "Halit Ergenç",
    "children": "3"
  },
  {
    "id": 135,
    "name": "Kenan İmirzalıoğlu",
    "fullName": "Kenan İmirzalıoğlu",
    "slug": "kenan-imirzalioglu",
    "country": "Turkey",
    "countrySlug": "turkey",
    "born": "June 18, 1974",
    "birthPlace": "Ankara, Turkey",
    "nationality": "Turkish",
    "profession": ["Actor", "Model"],
    "genre": ["Action", "Drama"],
    "bio": "Iconic lead of 'Ezel' and 'Karadayı'.",
    "image": "",
    "wikipedia": "https://en.wikipedia.org/wiki/Kenan_%C4%B0mirzal%C4%B1o%C4%9Flu",
    "movies": ["Kabadayı"],
    "dramas": ["Ezel", "Karadayı", "Alef"],
    "costars": ["Cansu Dere", "Bergüzar Korel"],
    "awards": [],
    "active": "1998–present",
    "netWorth": "$18 Million",
    "spouse": "Sinem Kobal",
    "children": "2"
  },
  {
    "id": 136,
    "name": "Cansu Dere",
    "fullName": "Cansu Dere",
    "slug": "cansu-dere",
    "country": "Turkey",
    "countrySlug": "turkey",
    "born": "October 14, 1980",
    "birthPlace": "Ankara, Turkey",
    "nationality": "Turkish",
    "profession": ["Actress", "Model"],
    "genre": ["Drama", "Thriller"],
    "bio": "Known for her roles in 'Sıla', 'Ezel', 'Anne', and 'Sadakatsiz'.",
    "image": "",
    "wikipedia": "https://en.wikipedia.org/wiki/Cansu_Dere",
    "movies": ["Behzat Ç. Seni Kalbime Gömdüm"],
    "dramas": ["Sadakatsiz", "Anne", "Ezel", "Sıla"],
    "costars": ["Caner Cindoruk", "Kenan İmirzalıoğlu"],
    "awards": [],
    "active": "2002–present",
    "netWorth": "$12 Million",
    "spouse": "None",
    "children": "None"
  },
  {
    "id": 137,
    "name": "Caner Cindoruk",
    "fullName": "Caner Cindoruk",
    "slug": "caner-cindoruk",
    "country": "Turkey",
    "countrySlug": "turkey",
    "born": "April 17, 1980",
    "birthPlace": "Adana, Turkey",
    "nationality": "Turkish",
    "profession": ["Actor"],
    "genre": ["Drama"],
    "bio": "Known as the 'Turkish George Clooney', star of 'Kadın' and 'Sadakatsiz'.",
    "image": "",
    "wikipedia": "https://en.wikipedia.org/wiki/Caner_Cindoruk",
    "movies": ["Gergedan Mevsimi"],
    "dramas": ["Sadakatsiz", "Kadın", "Muhteşem Yüzyıl: Kösem"],
    "costars": ["Cansu Dere", "Özge Özpirinçci"],
    "awards": [],
    "active": "2006–present",
    "netWorth": "$4 Million",
    "spouse": "None",
    "children": "None"
  },
  {
    "id": 138,
    "name": "Özge Özpirinçci",
    "fullName": "Özge Özpirinçci",
    "slug": "ozge-ozpirincci",
    "country": "Turkey",
    "countrySlug": "turkey",
    "born": "April 1, 1986",
    "birthPlace": "Istanbul, Turkey",
    "nationality": "Turkish",
    "profession": ["Actress"],
    "genre": ["Drama", "Comedy"],
    "bio": "Famous for 'Aşk Yeniden' and her powerful performance in 'Kadın'.",
    "image": "",
    "wikipedia": "https://en.wikipedia.org/wiki/%C3%96zge_%C3%96zpirin%C3%A7ci",
    "movies": ["Anadolu Kartalları"],
    "dramas": ["Kadın", "Aşk Yeniden", "Yakamoz S-245"],
    "costars": ["Caner Cindoruk", "Buğra Gülsoy"],
    "awards": ["Golden Butterfly Award"],
    "active": "2008–present",
    "netWorth": "$5 Million",
    "spouse": "Burak Yamantürk",
    "children": "1"
  },
  {
    "id": 139,
    "name": "Buğra Gülsoy",
    "fullName": "Buğra Gülsoy",
    "slug": "bugra-gulsoy",
    "country": "Turkey",
    "countrySlug": "turkey",
    "born": "February 22, 1982",
    "birthPlace": "Ankara, Turkey",
    "nationality": "Turkish",
    "profession": ["Actor", "Director", "Author"],
    "genre": ["Drama", "Historical"],
    "bio": "Multi-talented actor known for 'Kuzey Güney' and 'Uyanış: Büyük Selçuklu'.",
    "image": "",
    "wikipedia": "https://en.wikipedia.org/wiki/Bu%C4%9Fra_G%C3%BClsoy",
    "movies": ["Cebimdeki Yabancı"],
    "dramas": ["Kuzey Güney", "Fatmagül'ün Suçu Ne?", "Uyanış: Büyük Selçuklu"],
    "costars": ["Kıvanç Tatlıtuğ", "Beren Saat"],
    "awards": [],
    "active": "2004–present",
    "netWorth": "$6 Million",
    "spouse": "Nilüfer Gürbüz (div.)",
    "children": "1"
  },
  {
    "id": 140,
    "name": "Hande Soral",
    "fullName": "Hande Soral",
    "slug": "hande-soral",
    "country": "Turkey",
    "countrySlug": "turkey",
    "born": "February 2, 1987",
    "birthPlace": "Bursa, Turkey",
    "nationality": "Turkish",
    "profession": ["Actress"],
    "genre": ["Historical", "Drama"],
    "bio": "Known for 'Diriliş: Ertuğrul' and 'Bir Zamanlar Çukurova'.",
    "image": "",
    "wikipedia": "https://en.wikipedia.org/wiki/Hande_Soral",
    "movies": [],
    "dramas": ["Diriliş: Ertuğrul", "Bir Zamanlar Çukurova", "Ateş Kuşları"],
    "costars": ["Engin Altan Düzyatan", "Murat Ünalmış"],
    "awards": [],
    "active": "2008–present",
    "netWorth": "$3 Million",
    "spouse": "İsmail Demirci",
    "children": "1"
  },
  {
    "id": 141,
    "name": "Onur Tuna",
    "fullName": "Onur Tuna",
    "slug": "onur-tuna",
    "country": "Turkey",
    "countrySlug": "turkey",
    "born": "July 2, 1985",
    "birthPlace": "Çanakkale, Turkey",
    "nationality": "Turkish",
    "profession": ["Actor", "Singer"],
    "genre": ["Medical", "Drama"],
    "bio": "Famous for his piercing blue eyes and roles in 'Mucize Doktor' and 'Yasak Elma'.",
    "image": "",
    "wikipedia": "https://en.wikipedia.org/wiki/Onur_Tuna",
    "movies": ["Ağır Romantik"],
    "dramas": ["Mucize Doktor", "Mahkum", "Yasak Elma"],
    "costars": ["Taner Ölmez", "Sevda Erginci"],
    "awards": [],
    "active": "2011–present",
    "netWorth": "$4 Million",
    "spouse": "None",
    "children": "None"
  },
  {
    "id": 142,
    "name": "Taner Ölmez",
    "fullName": "Taner Ölmez",
    "slug": "taner-olmez",
    "country": "Turkey",
    "countrySlug": "turkey",
    "born": "August 9, 1986",
    "birthPlace": "Tunceli, Turkey",
    "nationality": "Turkish",
    "profession": ["Actor", "Musician"],
    "genre": ["Drama", "Medical"],
    "bio": "Gained critical acclaim for his portrayal of an autistic doctor in 'Mucize Doktor'.",
    "image": "",
    "wikipedia": "https://en.wikipedia.org/wiki/Taner_%C3%96lmez",
    "movies": ["Müslüm"],
    "dramas": ["Mucize Doktor", "Medcezir", "Muhteşem Yüzyıl: Kösem"],
    "costars": ["Onur Tuna", "Sinem Ünsal"],
    "awards": ["Golden Butterfly Award"],
    "active": "2009–present",
    "netWorth": "$5 Million",
    "spouse": "Ece Çeşmioğlu",
    "children": "1"
  },
  {
    "id": 143,
    "name": "Melis Sezen",
    "fullName": "Melis Sezen",
    "slug": "melis-sezen",
    "country": "Turkey",
    "countrySlug": "turkey",
    "born": "January 2, 1997",
    "birthPlace": "Istanbul, Turkey",
    "nationality": "Turkish",
    "profession": ["Actress"],
    "genre": ["Drama", "Thriller"],
    "bio": "Breakthrough role as Derin in the hit series 'Sadakatsiz'.",
    "image": "",
    "wikipedia": "https://en.wikipedia.org/wiki/Melis_Sezen",
    "movies": ["Şampiyon"],
    "dramas": ["Sadakatsiz", "Gülcemal", "Leke"],
    "costars": ["Cansu Dere", "Murat Ünalmış"],
    "awards": ["Golden Butterfly Rising Star"],
    "active": "2016–present",
    "netWorth": "$2 Million",
    "spouse": "None",
    "children": "None"
  },
  {
    "id": 144,
    "name": "Murat Ünalmış",
    "fullName": "Murat Ünalmış",
    "slug": "murat-unalmis",
    "country": "Turkey",
    "countrySlug": "turkey",
    "born": "April 23, 1981",
    "birthPlace": "Kayseri, Turkey",
    "nationality": "Turkish",
    "profession": ["Actor"],
    "genre": ["Drama", "Period"],
    "bio": "Known for his powerful presence in 'Bir Zamanlar Çukurova' and 'Yer Gök Aşk'.",
    "image": "",
    "wikipedia": "https://en.wikipedia.org/wiki/Murat_%C3%9Cnalm%C4%B1%C5%9F",
    "movies": ["Güneşi Gördüm"],
    "dramas": ["Bir Zamanlar Çukurova", "Yer Gök Aşk", "Gülcemal"],
    "costars": ["Hilal Altınbilek", "Melis Sezen"],
    "awards": [],
    "active": "2003–present",
    "netWorth": "$6 Million",
    "spouse": "Nutiye Akar",
    "children": "None"
  },
  {
    "id": 145,
    "name": "Hilal Altınbilek",
    "fullName": "Hilal Altınbilek",
    "slug": "hilal-altinbilek",
    "country": "Turkey",
    "countrySlug": "turkey",
    "born": "February 11, 1991",
    "birthPlace": "Izmir, Turkey",
    "nationality": "Turkish",
    "profession": ["Actress"],
    "genre": ["Drama"],
    "bio": "Rose to stardom with her lead role in 'Bir Zamanlar Çukurova'.",
    "image": "",
    "wikipedia": "https://en.wikipedia.org/wiki/Hilal_Alt%C4%B1nbilek",
    "movies": ["Çocuklar Sana Emanet"],
    "dramas": ["Bir Zamanlar Çukurova", "Karagül", "Şahane Hayatım"],
    "costars": ["Murat Ünalmış", "Onur Tuna"],
    "awards": [],
    "active": "2011–present",
    "netWorth": "$3 Million",
    "spouse": "None",
    "children": "None"
  },
  {
    "id": 146,
    "name": "Salih Bademci",
    "fullName": "Salih Bademci",
    "slug": "salih-bademci",
    "country": "Turkey",
    "countrySlug": "turkey",
    "born": "August 15, 1984",
    "birthPlace": "Izmir, Turkey",
    "nationality": "Turkish",
    "profession": ["Actor"],
    "genre": ["Drama", "Comedy"],
    "bio": "Critically acclaimed for his versatile roles in 'Kulüp' and 'İstanbullu Gelin'.",
    "image": "",
    "wikipedia": "https://en.wikipedia.org/wiki/Salih_Bademci",
    "movies": ["Bende Kal"],
    "dramas": ["Kulüp", "İstanbullu Gelin", "Kiralık Aşk", "Terzi"],
    "costars": ["Gökçe Bahadır", "Barış Arduç"],
    "awards": ["Golden Butterfly Award"],
    "active": "2006–present",
    "netWorth": "$4 Million",
    "spouse": "İmer Özgün",
    "children": "1"
  },
  {
    "id": 147,
    "name": "Gökçe Bahadır",
    "fullName": "Gökçe Bahadır",
    "slug": "gokce-bahadir",
    "country": "Turkey",
    "countrySlug": "turkey",
    "born": "November 9, 1981",
    "birthPlace": "Istanbul, Turkey",
    "nationality": "Turkish",
    "profession": ["Actress"],
    "genre": ["Drama"],
    "bio": "Talented actress known for 'Yaprak Dökümü' and the Netflix series 'Kulüp'.",
    "image": "",
    "wikipedia": "https://en.wikipedia.org/wiki/G%C3%B6k%C3%A7e_Bahad%C4%B1r",
    "movies": ["Dedemin İnsanları"],
    "dramas": ["Kulüp", "Ufak Tefek Cinayetler", "Evlilik Hakkında Her Şey"],
    "costars": ["Salih Bademci", "Barış Falay"],
    "awards": [],
    "active": "2000–present",
    "netWorth": "$6 Million",
    "spouse": "Emir Ersoy",
    "children": "None"
  },
  {
    "id": 148,
    "name": "Merve Dizdar",
    "fullName": "Merve Dizdar",
    "slug": "merve-dizdar",
    "country": "Turkey",
    "countrySlug": "turkey",
    "born": "June 25, 1986",
    "birthPlace": "Izmir, Turkey",
    "nationality": "Turkish",
    "profession": ["Actress"],
    "genre": ["Drama", "Arthouse"],
    "bio": "First Turkish woman to win Best Actress at the Cannes Film Festival (2023).",
    "image": "",
    "wikipedia": "https://en.wikipedia.org/wiki/Merve_Dizdar",
    "movies": ["Kuru Otlar Üstüne", "Eltilerin Savaşı"],
    "dramas": ["Masumlar Apartmanı", "Ömer"],
    "costars": ["Ezgi Mola", "Deniz Celiloğlu"],
    "awards": ["Cannes Film Festival - Best Actress"],
    "active": "2010–present",
    "netWorth": "$3 Million",
    "spouse": "Gürhan Altundaşar (div.)",
    "children": "None"
  },
  {
    "id": 149,
    "name": "Ezgi Mola",
    "fullName": "Ezgi Mola",
    "slug": "ezgi-mola",
    "country": "Turkey",
    "countrySlug": "turkey",
    "born": "March 29, 1983",
    "birthPlace": "Istanbul, Turkey",
    "nationality": "Turkish",
    "profession": ["Actress"],
    "genre": ["Comedy", "Drama"],
    "bio": "Beloved actress known for her comedic timing and dramatic depth in 'Masumlar Apartmanı'.",
    "image": "",
    "wikipedia": "https://en.wikipedia.org/wiki/Ezgi_Mola",
    "movies": ["Organize İşler", "Celal ile Ceren"],
    "dramas": ["Masumlar Apartmanı", "Erşan Kuneri"],
    "costars": ["Merve Dizdar", "Cem Yılmaz"],
    "awards": ["Golden Butterfly Award"],
    "active": "2000–present",
    "netWorth": "$8 Million",
    "spouse": "Mustafa Aksakallı",
    "children": "1"
  }
];

const existing = new Set(data.map(a=>a.slug));
const newActors = actors.filter(a=>!existing.has(a.slug));
const merged = [...data, ...newActors];

fs.writeFileSync('data/actors.json', JSON.stringify(merged, null, 2));

console.log('Added:', newActors.length, 'actors');
console.log('Total now:', merged.length);