const fs = require('fs');

const data = JSON.parse(fs.readFileSync('data/actors.json','utf8'));

const actors = [
  {
    "id": 330,
    "name": "Souad Hosny",
    "fullName": "Souad Hosny Al-Baba",
    "slug": "souad-hosny-legend",
    "country": "Egypt",
    "countrySlug": "egypt",
    "born": "January 26, 1943",
    "birthPlace": "Cairo, Egypt",
    "nationality": "Egyptian",
    "profession": ["Actress", "Singer"],
    "genre": ["Musical", "Drama", "Romance"],
    "bio": "Known as the 'Cinderella of Arab Cinema', she is one of the most influential actresses in the history of Middle Eastern film.",
    "image": "",
    "wikipedia": "https://en.wikipedia.org/wiki/Souad_Hosny",
    "movies": ["Watch Out for Zouzou", "The Nightmare", "Karnak"],
    "dramas": ["He and She"],
    "costars": ["Ahmed Zaki", "Rushdy Abaza"],
    "awards": ["Best Actress - multiple national awards"],
    "active": "1959–1991",
    "netWorth": "$10 Million",
    "spouse": "Ali Badrakhan (Ex)",
    "children": "None"
  },
  {
    "id": 331,
    "name": "Faten Hamama",
    "fullName": "Faten Ahmed Hamama",
    "slug": "faten-hamama",
    "country": "Egypt",
    "countrySlug": "egypt",
    "born": "May 27, 1931",
    "birthPlace": "Mansoura, Egypt",
    "nationality": "Egyptian",
    "profession": ["Actress", "Producer"],
    "genre": ["Drama", "Romance"],
    "bio": "Known as the 'Lady of the Arabic Screen', she was a symbol of elegance and a pioneer for women's rights in cinema.",
    "image": "",
    "wikipedia": "https://en.wikipedia.org/wiki/Faten_Hamama",
    "movies": ["The Nightingale's Prayer", "I am Free", "The Blazing Sun"],
    "dramas": ["Dameer Abla Hikmat"],
    "costars": ["Omar Sharif"],
    "awards": ["Star of the Century - Egyptian Film Organization"],
    "active": "1939–2000",
    "netWorth": "$20 Million",
    "spouse": "Omar Sharif (Ex)",
    "children": "2"
  },
  {
    "id": 332,
    "name": "Dawood Hussein",
    "fullName": "Dawood Hussein Khan",
    "slug": "dawood-hussein",
    "country": "Kuwait",
    "countrySlug": "kuwait",
    "born": "November 5, 1958",
    "birthPlace": "Kuwait City, Kuwait",
    "nationality": "Kuwaiti",
    "profession": ["Actor", "Comedian"],
    "genre": ["Comedy", "Drama"],
    "bio": "A legendary Kuwaiti comedian famous for his incredible ability to mimic celebrities and his long-running sketch shows.",
    "image": "",
    "wikipedia": "https://en.wikipedia.org/wiki/Dawood_Hussein",
    "movies": ["Atash"],
    "dramas": ["Garem El-Moustahil", "The Danger Zone"],
    "costars": ["Hayat Al-Fahad"],
    "awards": ["Best Comedy Actor - Gulf Festivals"],
    "active": "1977–present",
    "netWorth": "$8 Million",
    "spouse": "Unknown",
    "children": "2"
  },
  {
    "id": 333,
    "name": "Zaki Nassif",
    "fullName": "Zaki Nassif",
    "slug": "zaki-nassif-legacy",
    "country": "Lebanon",
    "countrySlug": "lebanon",
    "born": "July 4, 1916",
    "birthPlace": "Machghara, Lebanon",
    "nationality": "Lebanese",
    "profession": ["Composer", "Singer", "Actor"],
    "genre": ["Musical", "Folk"],
    "bio": "While primarily a composer, his presence in Lebanese cultural films and musical plays shaped the artistic identity of Lebanon.",
    "image": "",
    "wikipedia": "https://en.wikipedia.org/wiki/Zaki_Nassif",
    "movies": [],
    "dramas": [],
    "costars": ["Fairuz"],
    "awards": ["Order of Merit"],
    "active": "1950–2004",
    "netWorth": "$2 Million",
    "spouse": "Unknown",
    "children": "Unknown"
  },
  {
    "id": 334,
    "name": "Nadine Njeim",
    "fullName": "Nadine Nassib Njeim",
    "slug": "nadine-njeim-star",
    "country": "Lebanon",
    "countrySlug": "lebanon",
    "born": "February 7, 1984",
    "birthPlace": "Beirut, Lebanon",
    "nationality": "Lebanese",
    "profession": ["Actress"],
    "genre": ["Drama", "Romance"],
    "bio": "Former Miss Lebanon turned superstar actress, she is currently one of the most followed and successful actresses in the Arab world.",
    "image": "",
    "wikipedia": "https://en.wikipedia.org/wiki/Nadine_Nassib_Njeim",
    "movies": ["Sorry Mom"],
    "dramas": ["Al Hayba", "Five Thirty", "2020", "Zahra's Salon"],
    "costars": ["Qusai Khouli", "Taim Hasan"],
    "awards": ["Murex d'Or - Best Actress (Multiple)"],
    "active": "2004–present",
    "netWorth": "$7 Million",
    "spouse": "Hady Asmar (Ex)",
    "children": "2"
  },
  {
    "id": 335,
    "name": "Hany Ramzy",
    "fullName": "Hany Ramzy",
    "slug": "hany-ramzy",
    "country": "Egypt",
    "countrySlug": "egypt",
    "born": "November 12, 1964",
    "birthPlace": "Minya, Egypt",
    "nationality": "Egyptian",
    "profession": ["Actor", "Comedian"],
    "genre": ["Comedy", "Political Satire"],
    "bio": "Known for his tall stature and political comedy films that address social issues with a humorous twist.",
    "image": "",
    "wikipedia": "https://en.wikipedia.org/wiki/Hany_Ramzy_(actor)",
    "movies": ["Ghabi Menno Feeh", "Abu El Arabi", "Nems Bond"],
    "dramas": ["Mabrouk Galak Ala'a"],
    "costars": ["Nelly Karim"],
    "awards": [],
    "active": "1986–present",
    "netWorth": "$9 Million",
    "spouse": "Mona Mohab",
    "children": "2"
  },
  {
    "id": 336,
    "name": "Saba Mubarak",
    "fullName": "Saba Mubarak",
    "slug": "saba-mubarak-intl",
    "country": "Jordan",
    "countrySlug": "jordan",
    "born": "April 10, 1976",
    "birthPlace": "Anjara, Jordan",
    "nationality": "Jordanian",
    "profession": ["Actress", "Producer"],
    "genre": ["Drama", "Historical"],
    "bio": "A Pan-Arab superstar who has successfully crossed over into Egyptian cinema and international productions.",
    "image": "",
    "wikipedia": "https://en.wikipedia.org/wiki/Saba_Mubarak",
    "movies": ["The Guest", "Daughters of Abdul-Rahman"],
    "dramas": ["Afrah Al-Qobba", "The Invasion", "Suits Arabia"],
    "costars": ["Asser Yassin"],
    "awards": ["Best Actress - Jordan Film Festival"],
    "active": "1998–present",
    "netWorth": "$5 Million",
    "spouse": "Chawki Mejri (Ex)",
    "children": "1"
  },
  {
    "id": 337,
    "name": "Maxim Khalil",
    "fullName": "Maxim Khalil",
    "slug": "maxim-khalil",
    "country": "Syria",
    "countrySlug": "syria",
    "born": "November 7, 1978",
    "birthPlace": "Homs, Syria",
    "nationality": "Syrian",
    "profession": ["Actor"],
    "genre": ["Drama", "Romance"],
    "bio": "A versatile Syrian actor known for his deep emotional performances and roles in major Pan-Arab TV hits.",
    "image": "",
    "wikipedia": "https://en.wikipedia.org/wiki/Maxim_Khalil",
    "movies": [],
    "dramas": ["Ruby", "The Platform", "Siraa Ala El Remal"],
    "costars": ["Sirusho"],
    "awards": ["Murex d'Or - Best Arab Actor"],
    "active": "2000–present",
    "netWorth": "$4 Million",
    "spouse": "Sawsan Arsheed",
    "children": "3"
  },
  {
    "id": 338,
    "name": "Maguy Bou Ghosn",
    "fullName": "Maguy Bou Ghosn",
    "slug": "maguy-bou-ghosn",
    "country": "Lebanon",
    "countrySlug": "lebanon",
    "born": "September 18, 1975",
    "birthPlace": "Bsalim, Lebanon",
    "nationality": "Lebanese",
    "profession": ["Actress", "Producer"],
    "genre": ["Drama", "Comedy"],
    "bio": "One of the most powerful women in Lebanese entertainment today, known for her 'Till Death' (Lel Mawt) series.",
    "image": "",
    "wikipedia": "https://en.wikipedia.org/wiki/Maguy_Bou_Ghosn",
    "movies": ["Vitamin", "Bebe"],
    "dramas": ["Till Death", "Caramel"],
    "costars": ["Daniella Rahme"],
    "awards": ["Murex d'Or"],
    "active": "1991–present",
    "netWorth": "$6 Million",
    "spouse": "Jamal Sannan",
    "children": "2"
  },
  {
    "id": 339,
    "name": "Ahmed Helmy",
    "fullName": "Ahmed Mohamed Helmy",
    "slug": "ahmed-helmy-comedian",
    "country": "Egypt",
    "countrySlug": "egypt",
    "born": "November 18, 1969",
    "birthPlace": "Banha, Egypt",
    "nationality": "Egyptian",
    "profession": ["Actor", "Producer", "Judge"],
    "genre": ["Comedy", "Drama"],
    "bio": "Egypt's most beloved modern comedian, known for his witty, family-friendly humor and judging on Arabs Got Talent.",
    "image": "",
    "wikipedia": "https://en.wikipedia.org/wiki/Ahmed_Helmy",
    "movies": ["Zaki Chan", "Assal Eswed", "X-Large"],
    "dramas": ["Al-Gama'a"],
    "costars": ["Mona Zaki"],
    "awards": ["Best Actor - Cairo Film Festival"],
    "active": "1993–present",
    "netWorth": "$18 Million",
    "spouse": "Mona Zaki",
    "children": "3"
  },
  {
    "id": 340,
    "name": "Mona Zaki",
    "fullName": "Mona Ali Mohamed Zaki",
    "slug": "mona-zaki-actress",
    "country": "Egypt",
    "countrySlug": "egypt",
    "born": "November 18, 1976",
    "birthPlace": "Cairo, Egypt",
    "nationality": "Egyptian",
    "profession": ["Actress"],
    "genre": ["Drama", "Thriller"],
    "bio": "A leading lady of her generation, highly respected for her intense dramatic performances and choice of complex scripts.",
    "image": "",
    "wikipedia": "https://en.wikipedia.org/wiki/Mona_Zaki",
    "movies": ["Sahar el Layali", "Dam el Ghazal", "Perfect Strangers"],
    "dramas": ["Newton's Cradle", "Afrah Al-Qobba"],
    "costars": ["Ahmed Helmy", "Ahmed El Sakka"],
    "awards": ["Best Actress - various festivals"],
    "active": "1991–present",
    "netWorth": "$15 Million",
    "spouse": "Ahmed Helmy",
    "children": "3"
  },
  {
    "id": 341,
    "name": "Tariq Al-Ali",
    "fullName": "Tariq Hamoud Al-Ali",
    "slug": "tariq-al-ali",
    "country": "Kuwait",
    "countrySlug": "kuwait",
    "born": "January 18, 1966",
    "birthPlace": "Al Jahra, Kuwait",
    "nationality": "Kuwaiti",
    "profession": ["Actor", "Comedian"],
    "genre": ["Comedy", "Theater"],
    "bio": "A giant of Kuwaiti theater, known for his improvisational skills and high-energy stage comedies.",
    "image": "",
    "wikipedia": "https://en.wikipedia.org/wiki/Tariq_Al-Ali",
    "movies": ["Hello Cairo"],
    "dramas": ["Al-Faltah"],
    "costars": ["Hayat Al-Fahad"],
    "awards": [],
    "active": "1983–present",
    "netWorth": "$12 Million",
    "spouse": "Unknown",
    "children": "4"
  },
  {
    "id": 342,
    "name": "Nasser Al-Qasabi",
    "fullName": "Nasser Al-Qasabi",
    "slug": "nasser-al-qasabi-star",
    "country": "Saudi Arabia",
    "countrySlug": "saudi-arabia",
    "born": "November 28, 1961",
    "birthPlace": "Riyadh, Saudi Arabia",
    "nationality": "Saudi",
    "profession": ["Actor", "Comedian"],
    "genre": ["Comedy", "Satire"],
    "bio": "One of the most famous comedians in the Arab world, best known for his satirical show 'Tash ma Tash' which tackled social issues in Saudi Arabia.",
    "image": "",
    "wikipedia": "https://en.wikipedia.org/wiki/Nasser_Al_Qasabi",
    "movies": [],
    "dramas": ["Tash ma Tash", "Selfie", "Al-Asouf"],
    "costars": ["Abdullah Al-Sadhan"],
    "awards": ["Best Arab Actor - Various"],
    "active": "1981–present",
    "netWorth": "$25 Million",
    "spouse": "Badriyah Al-Bishr",
    "children": "3"
  },
  {
    "id": 343,
    "name": "Sulafa Memar",
    "fullName": "Sulafa Memar",
    "slug": "sulafa-memar",
    "country": "Syria",
    "countrySlug": "syria",
    "born": "April 26, 1976",
    "birthPlace": "Damascus, Syria",
    "nationality": "Syrian",
    "profession": ["Actress"],
    "genre": ["Drama"],
    "bio": "Known for her stunning features and even more impressive acting skills, she is a mainstay of Syrian dramatic excellence.",
    "image": "",
    "wikipedia": "https://en.wikipedia.org/wiki/Sulafa_Memar",
    "movies": ["Under the Ceiling"],
    "dramas": ["Zaman Al-Ar", "Al-Khawaja Abdel Qader", "Haret Al-Quba"],
    "costars": ["Abbas Al-Nouri"],
    "awards": ["Best Actress - Adonia Awards"],
    "active": "1994–present",
    "netWorth": "$4.5 Million",
    "spouse": "Saif Al-Din Subai'i (Ex)",
    "children": "1"
  },
  {
    "id": 344,
    "name": "Cyrine Abdelnour",
    "fullName": "Cyrine Abdelnour",
    "slug": "cyrine-abdelnour",
    "country": "Lebanon",
    "countrySlug": "lebanon",
    "born": "February 21, 1977",
    "birthPlace": "Abadiyeh, Lebanon",
    "nationality": "Lebanese",
    "profession": ["Actress", "Singer", "Model"],
    "genre": ["Drama", "Romance"],
    "bio": "A multi-talented star who transitioned from singing and modeling to becoming one of Lebanon's top dramatic actresses.",
    "image": "",
    "wikipedia": "https://en.wikipedia.org/wiki/Cyrine_Abdelnour",
    "movies": ["Ramadan Mabrouk Abul-Alamein Hamouda"],
    "dramas": ["Al-Adham", "Ruby", "Al Hayba - Al Hasad"],
    "costars": ["Taim Hasan"],
    "awards": ["Murex d'Or (Multiple)"],
    "active": "1994–present",
    "netWorth": "$6 Million",
    "spouse": "Farid Rahme",
    "children": "2"
  },
  {
    "id": 345,
    "name": "Mohamed Henedy",
    "fullName": "Mohamed Henedy Ahmed Abdel Gawad",
    "slug": "mohamed-henedy",
    "country": "Egypt",
    "countrySlug": "egypt",
    "born": "February 1, 1965",
    "birthPlace": "Giza, Egypt",
    "nationality": "Egyptian",
    "profession": ["Actor", "Comedian"],
    "genre": ["Comedy"],
    "bio": "The man who triggered the 'comedy revolution' in Egypt in the late 90s. He is known for his short stature and massive comedic impact.",
    "image": "",
    "wikipedia": "https://en.wikipedia.org/wiki/Mohamed_Henedy",
    "movies": ["Sa'edi in the American University", "Hammam in Amsterdam"],
    "dramas": ["Ardh Al-Nifaq"],
    "costars": ["Mona Zaki"],
    "awards": ["Best Actor - various Egyptian festivals"],
    "active": "1988–present",
    "netWorth": "$22 Million",
    "spouse": "Abeer El-Sari",
    "children": "3"
  },
  {
    "id": 346,
    "name": "Eyad Nassar",
    "fullName": "Eyad Nassar",
    "slug": "eyad-nassar-actor",
    "country": "Jordan",
    "countrySlug": "jordan",
    "born": "November 9, 1971",
    "birthPlace": "Amman, Jordan",
    "nationality": "Jordanian-Egyptian",
    "profession": ["Actor"],
    "genre": ["Drama", "Thriller"],
    "bio": "A Jordanian actor who achieved massive success in Egypt, known for playing historical figures and intense characters.",
    "image": "",
    "wikipedia": "https://en.wikipedia.org/wiki/Eyad_Nassar",
    "movies": ["The Passage", "The Blue Elephant 2"],
    "dramas": ["Al-Gama'a", "The Seven Commandments"],
    "costars": ["Mona Zaki"],
    "awards": ["Best Actor - Cairo Media Festival"],
    "active": "1995–present",
    "netWorth": "$6 Million",
    "spouse": "Sheira El-Sebaie",
    "children": "3"
  },
  {
    "id": 347,
    "name": "Abdelhadi El Sonni",
    "fullName": "Abdelhadi El Sonni",
    "slug": "abdelhadi-el-sonni",
    "country": "Morocco",
    "countrySlug": "morocco",
    "born": "January 1, 1950",
    "birthPlace": "Casablanca, Morocco",
    "nationality": "Moroccan",
    "profession": ["Actor"],
    "genre": ["Drama"],
    "bio": "A veteran actor in Moroccan cinema and television, respected for his character roles.",
    "image": "",
    "wikipedia": "https://en.wikipedia.org/wiki/Cinema_of_Morocco",
    "movies": [],
    "dramas": [],
    "costars": [],
    "awards": [],
    "active": "1975–present",
    "netWorth": "$1 Million",
    "spouse": "Unknown",
    "children": "2"
  },
  {
    "id": 348,
    "name": "Amr Waked",
    "fullName": "Amr Waked",
    "slug": "amr-waked-intl",
    "country": "Egypt",
    "countrySlug": "egypt",
    "born": "April 12, 1973",
    "birthPlace": "Cairo, Egypt",
    "nationality": "Egyptian",
    "profession": ["Actor"],
    "genre": ["Drama", "International"],
    "bio": "One of the few Egyptian actors with a significant Hollywood career, starring alongside stars like George Clooney and Scarlett Johansson.",
    "image": "",
    "wikipedia": "https://en.wikipedia.org/wiki/Amr_Waked",
    "movies": ["Syriana", "Lucy", "Salmon Fishing in the Yemen"],
    "dramas": ["Ramy", "Marco Polo"],
    "costars": ["Scarlett Johansson"],
    "awards": [],
    "active": "1999–present",
    "netWorth": "$5 Million",
    "spouse": "Unknown",
    "children": "1"
  },
  {
    "id": 349,
    "name": "Yousra El Lozy",
    "fullName": "Yousra El Lozy",
    "slug": "yousra-el-lozy",
    "country": "Egypt",
    "countrySlug": "egypt",
    "born": "August 8, 1985",
    "birthPlace": "Cairo, Egypt",
    "nationality": "Egyptian",
    "profession": ["Actress"],
    "genre": ["Drama", "Indie"],
    "bio": "Started her career with director Youssef Chahine and has since become a popular face in mainstream TV and cinema.",
    "image": "",
    "wikipedia": "https://en.wikipedia.org/wiki/Yousra_El_Lozy",
    "movies": ["Alexandria... New York", "Stolen Kisses"],
    "dramas": ["Vertigo", "Adam and Jamila"],
    "costars": [],
    "awards": [],
    "active": "2004–present",
    "netWorth": "$3.5 Million",
    "spouse": "Ahmed El-Drobi",
    "children": "2"
  },
  {
    "id": 350,
    "name": "Hassan Youssef",
    "fullName": "Hassan Youssef",
    "slug": "hassan-youssef-vet",
    "country": "Egypt",
    "countrySlug": "egypt",
    "born": "April 14, 1934",
    "birthPlace": "Cairo, Egypt",
    "nationality": "Egyptian",
    "profession": ["Actor", "Director"],
    "genre": ["Romance", "Religious Drama"],
    "bio": "A romantic icon in the 1960s who later became famous for portraying religious figures like Imam Al-Shafi'i.",
    "image": "",
    "wikipedia": "https://en.wikipedia.org/wiki/Hassan_Youssef_(actor)",
    "movies": ["The Three Devils"],
    "dramas": ["Imam Al-Shafi'i"],
    "costars": ["Shams al-Baroudi"],
    "awards": [],
    "active": "1959–present",
    "netWorth": "$8 Million",
    "spouse": "Shams al-Baroudi",
    "children": "4"
  },
  {
    "id": 351,
    "name": "Abdel Moneim Madbouly",
    "fullName": "Abdel Moneim Madbouly",
    "slug": "abdel-moneim-madbouly",
    "country": "Egypt",
    "countrySlug": "egypt",
    "born": "December 28, 1921",
    "birthPlace": "Cairo, Egypt",
    "nationality": "Egyptian",
    "profession": ["Actor", "Comedian"],
    "genre": ["Comedy", "Theater"],
    "bio": "A legend of Egyptian comedy and theater, known for his unique comedic school called 'Madboulysm'.",
    "image": "",
    "wikipedia": "https://en.wikipedia.org/wiki/Abdel_Moneim_Madbouly",
    "movies": ["The Grandson"],
    "dramas": ["Baba Abdo"],
    "costars": ["Fouad el-Mohandes"],
    "awards": [],
    "active": "1950–2006",
    "netWorth": "$5 Million",
    "spouse": "Unknown",
    "children": "3"
  },
  {
    "id": 352,
    "name": "Nabil El Halafawy",
    "fullName": "Nabil El Halafawy",
    "slug": "nabil-el-halafawy",
    "country": "Egypt",
    "countrySlug": "egypt",
    "born": "April 22, 1947",
    "birthPlace": "Cairo, Egypt",
    "nationality": "Egyptian",
    "profession": ["Actor"],
    "genre": ["Drama", "Historical"],
    "bio": "A high-caliber dramatic actor known for his intellectual depth and masterful performances in television.",
    "image": "",
    "wikipedia": "https://en.wikipedia.org/wiki/Cinema_of_Egypt",
    "movies": ["The Road to Eilat"],
    "dramas": ["Raafat Al-Haggan"],
    "costars": ["Mahmoud Abdel Aziz"],
    "awards": [],
    "active": "1970–present",
    "netWorth": "$4 Million",
    "spouse": "Ghada Aboud",
    "children": "2"
  },
  {
    "id": 353,
    "name": "Bassem Sabri",
    "fullName": "Bassem Sabri",
    "slug": "bassem-sabri",
    "country": "Egypt",
    "countrySlug": "egypt",
    "born": "January 1, 1970",
    "birthPlace": "Cairo, Egypt",
    "nationality": "Egyptian",
    "profession": ["Actor"],
    "genre": ["Drama"],
    "bio": "An Egyptian actor who worked primarily in the late 90s and early 2000s.",
    "image": "",
    "wikipedia": "https://en.wikipedia.org/wiki/Cinema_of_Egypt",
    "movies": [],
    "dramas": [],
    "costars": [],
    "awards": [],
    "active": "1995–2010",
    "netWorth": "$1 Million",
    "spouse": "Unknown",
    "children": "Unknown"
  },
  {
    "id": 354,
    "name": "Zubair Al-Rai",
    "fullName": "Zubair Al-Rai",
    "slug": "zubair-al-rai",
    "country": "Jordan",
    "countrySlug": "jordan",
    "born": "January 1, 1980",
    "birthPlace": "Amman, Jordan",
    "nationality": "Jordanian",
    "profession": ["Actor"],
    "genre": ["Drama"],
    "bio": "A Jordanian actor active in local television drama.",
    "image": "",
    "wikipedia": "https://en.wikipedia.org/wiki/Television_in_Jordan",
    "movies": [],
    "dramas": [],
    "costars": [],
    "awards": [],
    "active": "2005–present",
    "netWorth": "$500,000",
    "spouse": "Unknown",
    "children": "1"
  },
  {
    "id": 355,
    "name": "Nidal Al-Khatib",
    "fullName": "Nidal Al-Khatib",
    "slug": "nidal-al-khatib",
    "country": "Jordan",
    "countrySlug": "jordan",
    "born": "January 1, 1975",
    "birthPlace": "Amman, Jordan",
    "nationality": "Jordanian",
    "profession": ["Actor"],
    "genre": ["Drama", "Bedouin"],
    "bio": "Known for his roles in Jordanian Bedouin dramas.",
    "image": "",
    "wikipedia": "https://en.wikipedia.org/wiki/Television_in_Jordan",
    "movies": [],
    "dramas": [],
    "costars": [],
    "awards": [],
    "active": "1998–present",
    "netWorth": "$1 Million",
    "spouse": "Unknown",
    "children": "2"
  },
  {
    "id": 356,
    "name": "Zubair Al-Mufti",
    "fullName": "Zubair Al-Mufti",
    "slug": "zubair-al-mufti",
    "country": "Syria",
    "countrySlug": "syria",
    "born": "January 1, 1982",
    "birthPlace": "Damascus, Syria",
    "nationality": "Syrian",
    "profession": ["Actor"],
    "genre": ["Drama"],
    "bio": "A character actor in Syrian dramas.",
    "image": "",
    "wikipedia": "https://en.wikipedia.org/wiki/Cinema_of_Syria",
    "movies": [],
    "dramas": [],
    "costars": [],
    "awards": [],
    "active": "2010–present",
    "netWorth": "$700,000",
    "spouse": "None",
    "children": "None"
  },
  {
    "id": 357,
    "name": "Nidal Al-Saidi",
    "fullName": "Nidal Al-Saidi",
    "slug": "nidal-al-saidi-tunis",
    "country": "Tunisia",
    "countrySlug": "tunisia",
    "born": "January 1, 1988",
    "birthPlace": "Tunis, Tunisia",
    "nationality": "Tunisian",
    "profession": ["Actor"],
    "genre": ["Drama"],
    "bio": "A young Tunisian actor with several popular television roles.",
    "image": "",
    "wikipedia": "https://en.wikipedia.org/wiki/Cinema_of_Tunisia",
    "movies": [],
    "dramas": ["Awlad Moufida"],
    "costars": [],
    "awards": [],
    "active": "2010–present",
    "netWorth": "$1 Million",
    "spouse": "None",
    "children": "None"
  },
  {
    "id": 358,
    "name": "Zubair Al-Fayez",
    "fullName": "Zubair Al-Fayez",
    "slug": "zubair-al-fayez",
    "country": "Saudi Arabia",
    "countrySlug": "saudi-arabia",
    "born": "January 1, 1980",
    "birthPlace": "Riyadh, Saudi Arabia",
    "nationality": "Saudi",
    "profession": ["Actor"],
    "genre": ["Comedy"],
    "bio": "A Saudi actor active in the comedic television scene.",
    "image": "",
    "wikipedia": "https://en.wikipedia.org/wiki/Cinema_of_Saudi_Arabia",
    "movies": [],
    "dramas": [],
    "costars": [],
    "awards": [],
    "active": "2005–present",
    "netWorth": "$1.5 Million",
    "spouse": "Unknown",
    "children": "2"
  },
  {
    "id": 359,
    "name": "Nidal Al-Rai",
    "fullName": "Nidal Al-Rai",
    "slug": "nidal-al-rai",
    "country": "Lebanon",
    "countrySlug": "lebanon",
    "born": "January 1, 1985",
    "birthPlace": "Beirut, Lebanon",
    "nationality": "Lebanese",
    "profession": ["Actor"],
    "genre": ["Drama"],
    "bio": "A Lebanese actor working in modern drama series.",
    "image": "",
    "wikipedia": "https://en.wikipedia.org/wiki/Cinema_of_Lebanon",
    "movies": [],
    "dramas": [],
    "costars": [],
    "awards": [],
    "active": "2015–present",
    "netWorth": "$500,000",
    "spouse": "None",
    "children": "None"
  }
];

const existing = new Set(data.map(a=>a.slug));
const newActors = actors.filter(a=>!existing.has(a.slug));
const merged = [...data, ...newActors];
fs.writeFileSync('data/actors.json', JSON.stringify(merged, null, 2));
console.log('Added:', newActors.length, 'actors');
console.log('Total now:', merged.length);